efdevcon/DIPs

DIPs/DIP-0.md
Update <DIP format> section, Put Authors after Tags to match DIP-0 format
=> Update <DIP format> section, Put Authors after Tags to match DIP-0 format

.github/workflows/linkcheck.yml
Let's automate some of our reviewer tasks - starting with a link-checker
=> Add link checker

DIPs/DIP-4.md
The Devcon team is really excited to have a treasure hunt game created for Devcon 6!
=> Treasure Hunt Game accepted for Devcon 6

DIPs/DIP-1.md
The Devcon team is really excited to have CO2ken onboard to help counter our CO2 emissions!
=> Co2ken accepted for Devcon 6

DIPs/DIP-11.md, checklist.md
A crypto-onboarding escape room proposal.
=> DIP-11: A Crypto-Onboarding Escape Room

DIPs/DIP-12.md
DIP-12 extends [CO2ken's original DIP-1](https://github.com/efdevcon/DIPs/blob/master/DIPs/DIP-1.md) and explains how contributions are collected and allocated to carbon projects using a DAO
=> Added DIP-12 which extends DIP-1

DIPs/DIP-13.md
Hi guys,
Many thanks for all of the detailed responses and explanations. We’ve been deliberating as a team on the various proposals we’ve received, and sadly we’ve decided not to move forward with GET Protocol and GUTS Ticketing for *this coming* Devcon. 
We do however really appreciate the proposal and the time you spent to walk us through your solution. It’s impressive what you guys have built and I think it suits some particular needs of the event ecosystem very well. 
For Devcon however a few of our values directed us to pursue other options:
— We try to promote FOSS software and mentality whenever we can, and some of our other options satisfy this goal better. We understand the GET Protocol is open source, but the GUTS ticketing app being closed source is a downside from Devcon’s …
=> Update status to rejected for Devcon 6

DIPs/DIP-6.md
Updated the old links as we moved the tokenscript website to a new domain.
=> Update DIP-6 with latest links

README.md
Added 'post idea to forum' step for contributing.
Move some of the specific format stuff (name DIP a certain way, etc) to the DIP-0 (via PR
=> Simplify DIP process based on feedback

DIPs/DIP-0.md
Copy changes, some minor process changes to make it simpler.
=> Make more clear the DIP process

.github/wordlist.txt, DIPs/DIP-17.md
Add proposal to make Devcon6 carbon neutral. Forum discussion:
https://forum.devcon.org/t/lets-make-devcon6-carbon-neutral-a-step-towards-implementing-dip-1-dip-12/400?u=danceratopz
=> DIP-17: Make Devcon6 Carbon Neutral - A step towards implementing DIP-1/DIP-12

DIPs/DIP-24, DIPs/DIP-24.md
Thank you for accepting our proposal to lead the Women Leaders in Web3 community hub at Devcon this year. We are super excited and have created DIP-24 to support our proposal. Let us know if you have any questions. You can view our accepted proposal here: https://forum.devcon.org/t/community-hub-proposal-women-leaders-in-web3/839/26
=> Create DIP-24: Women Leaders in Web3 Community Hub at Devcon

DIPs/DIP-20.md
Submitting the proposal for DIP-20: OPEN SOURCED ART from the HEART
=> Submission DIP-20

DIPs/DIP-23.md
=> Add DIP-23

DIPs/DIP-21.md, DIPs/DIP-CommunityHub-BuildingWeb3DeveloperCommunitiesHub.md
This DIP is for a Community Hub dedicated to building Web3 developer communities. The RFP discussion and support for it can be found [here](https://forum.devcon.org/t/building-web3-developer-communities-hub-proposal/849). 
Please reach out to sunny@superfluid.finance with any questions. All of us involved with this proposal appreciate your consideration!
_While this DIP has not been formally provided a number, I am assuming No. 21 in sequence off of numbers from other open PRs._
=> Create DIP-21: Community Hub - Building Web3 Developer Communities

DIPs/DIP-5.md
=> Postpone DIP-5

DIPs/DIP-25.md, DIPs/Live UX Research
=> Create Live UX Research

DIPs/DIP-21.md
https://forum.devcon.org/t/building-web3-developer-communities-hub-proposal/849/19
=> Reject DIP-21

DIPs/DIP-24.md
- Adding ``Community Hub`` tag
- Adjusting resources to what is offered as per [Community Hubs Production Guide](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/9188bbdc-de3a-4cad-89f3-2f639beffb50/COMMUNITY_HUBS_GUIDE_DEVCON_6.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20220929%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20220929T124335Z&X-Amz-Expires=86400&X-Amz-Signature=b6f6fa004afcdcce7690bdb5ad6b19322383d957f2747b26e168ccdeae488af4&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22COMMUNITY_HUBS_GUIDE_DEVCON_6.pdf%22&x-id=GetObject). Note that anything not included in this guide needs to be provided by the organizers of the respective Community Hub.
- Adjusting the resources …
=> Updating DIP-24 according to Production Guidelines

DIPs/DIP-22.md
- Adding ``Community Hub`` tag
- Updating production details as outlined in the [Production Guide](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/9188bbdc-de3a-4cad-89f3-2f639beffb50/COMMUNITY_HUBS_GUIDE_DEVCON_6.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20220929%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20220929T124335Z&X-Amz-Expires=86400&X-Amz-Signature=b6f6fa004afcdcce7690bdb5ad6b19322383d957f2747b26e168ccdeae488af4&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22COMMUNITY_HUBS_GUIDE_DEVCON_6.pdf%22&x-id=GetObject)
- Please make sure to respect the Community Hub Guidelines re. no speakers or mics allowed! (Pls don't disturb your Community Hub neighbors. :))
=> Update DIP-22 with production details

README.md
The current wording pushes towards addition - rewording to unbias and encourage DIPs to subtract rather than add to DEVCon
=> Encourage subtraction

.github/ISSUE_TEMPLATE/issue_report.md, .github/pull_request_template.md
=> Add Issue and PR templates (#63)

README.md
Previous link went to Devcon Homepage since the Contribute page no longer exists.
=> Updated DIPs website link

DIPs/DIP-43.md
This proposal recommends integrating Reclaim Protocol to enhance attendee verification and inclusivity. Our solution offers multiple options for verifying nationality, providing flexibility and speeding up the process to just a few seconds. Users can leverage it's zkTLS infrastructure to generate verified credentials from any website within few seconds.
=> DIP-43: Proposal to Integrate Reclaim Protocol for Identity Verification

DIPs/DIP-47, DIPs/DIP-47.md
https://forum.devcon.org/t/dip-47-frogcrypto-2/3866
=> DIP-47: FROGCRYPTO 2

DIPs/DIP-55.md
Initial commit to the DIP about Awareness Security Campaigns.
Adding a new DIP.
N/A
=> DIP-55: A.L.E.R.T.

DIPs/DIP-62.md
=> Rework DIP-56

DIPs/DIP-0.md, DIPs/DIP-1.md, DIPs/DIP-16.md, DIPs/DIP-18.md, DIPs/DIP-21.md, DIPs/DIP-28.md, DIPs/DIP-38.md, DIPs/DIP-46.md, DIPs/DIP-58.md, DIPs/DIP-59.md, DIPs/DIP-60.md
This pull request corrects typos and minor grammatical errors in multiple DIP markdown files to improve readability and professionalism. The affected files are:
- DIP-0.md
- DIP-1.md
- DIP-16.md
- DIP-18.md
- DIP-21.md
- DIP-28.md
- DIP-38.md
- DIP-46.md
- DIP-58.md
- DIP-59.md
- DIP-60.md
N/A
=> DIP-X: Correct Typos in Multiple DIP Files

DIPs/DIP-65.md
Provide a seamless housing reservation experience for **Devcon[nect]**. This platform, developed by **Betrusty**, allows attendees to **securely and reliably** book verified accommodations during events using decentralized identity and cryptocurrency payments.
https://forum.devcon.org/t/housing-devconnect-argentina-2025/6747
=> DIP-65: Provide a seamless housing reservation experience for Devcon[nect].
